apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: barista
spec:
  template:
    spec:
      containers:
      - name: user-container
        image: image-registry.openshift-image-registry.svc:5000/user19-dev-coffeeshop/barista:dev-2021-04-23-14-10-26

