apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coffee-shop-database
  namespace: wk12-argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: wk12-prod-coffeeshop
  project: coffee-shop
  source:
    chart: coffee-shop-postgresql
    helm:
      parameters:
      - forceString: true
        name: fullnameOverride
        value: coffee-shop-database
      - forceString: true
        name: openshiftApplicationName
        value: coffee-shop
      - forceString: true
        name: credentials.database
        value: coffeeshop
      - forceString: true
        name: credentials.username
        value: coffee
      - forceString: true
        name: credentials.password
        value: coffee
    repoURL: http://homework-nexus.gpte-hw-cicd.svc:8081/repository/helm
    targetRevision: 1.0.0
