apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: coffee-shop
spec:
  serviceAccountName: pipeline
  triggers:
  - name: coffee-shop
    bindings:
    - ref: coffee-shop-binding
    template:
      ref: coffee-shop-template

