apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: coffee-shop-binding
spec:
  params:
  - name: git-repo-url
    value: $(body.repository.clone_url)
  - name: git-revision
    value: $(body.after)

